// <auto-generated />
namespace WebBanHangOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ngay22thang2nam2024 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ngay22thang2nam2024));
        
        string IMigrationMetadata.Id
        {
            get { return "202402220844210_ngay22thang2nam2024"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
